import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

/**
 * Copy the build into a live vault when one is named.
 *
 * Obsidian loads a plugin from `<vault>/.obsidian/plugins/<id>/`, not from this
 * repository, so a build that stops at `main.js` has changed nothing the user
 * can see. There was no deploy step at all, which meant the running plugin and
 * the source could diverge silently and only a byte comparison would say so.
 *
 * The vault path is supplied rather than hard-coded: it is irreducibly
 * particular to a machine, so it belongs in the environment, not in the build.
 *   OBSIDIAN_PLUGIN_DIR=".../.obsidian/plugins/problem-notes" npm run build
 */
async function deploy() {
	const target = process.env.OBSIDIAN_PLUGIN_DIR;
	if (!target) return;
	const { copyFile, mkdir } = await import("node:fs/promises");
	await mkdir(target, { recursive: true });
	for (const file of ["main.js", "manifest.json", "styles.css"]) {
		await copyFile(file, `${target}/${file}`);
	}
	console.log(`deployed main.js, manifest.json, styles.css -> ${target}`);
}

if (prod) {
	await context.rebuild();
	await deploy();
	process.exit(0);
} else {
	await context.watch();
}
